const ROLE_MULTIPLIERS = {
  TOP: {
    kda: 1.1,
    economy: 1.05,
    map_awareness: 0.9,
    utility: 0.6,
    damage: 1.15,
    tanking: 1.0,
    objectives: 1.2,
    early_game: 1.05,
  },
  JUNGLE: {
    kda: 1.2,
    economy: 0.7,
    map_awareness: 1.4,
    utility: 0.8,
    damage: 1.0,
    tanking: 0.8,
    objectives: 1.4,
    early_game: 1.3,
  },
  MIDDLE: {
    kda: 1.0,
    economy: 1.1,
    map_awareness: 1.2,
    utility: 1.0,
    damage: 1.05,
    tanking: 0.8,
    objectives: 1.0,
    early_game: 1.1,
  },
  BOTTOM: {
    kda: 1.2,
    economy: 1.3,
    map_awareness: 1.1,
    utility: 0.7,
    damage: 1.4,
    tanking: 0.6,
    objectives: 0.9,
    early_game: 1.0,
  },
  UTILITY: {
    kda: 0.7,
    economy: 0.4,
    map_awareness: 1.8,
    utility: 1.8,
    damage: 0.5,
    tanking: 1.1,
    objectives: 0.7,
    early_game: 0.8,
  },
  UNKNOWN: {
    kda: 1.0,
    economy: 1.0,
    map_awareness: 1.0,
    utility: 1.0,
    damage: 1.0,
    tanking: 1.0,
    objectives: 1.0,
    early_game: 1.0,
  },
};

const DEATH_TOLERANCE = {
  TOP: 1.0,
  JUNGLE: 1.05,
  MIDDLE: 1.0,
  BOTTOM: 1.15,
  UTILITY: 0.8,
  UNKNOWN: 1.0,
};

const OPSCORE_V2 = {
  curve: {
    targetAtExpected: 0.7,
    sharpness: 2,
    overflowLambda: 0.5,
    subcategoryCap: 2.2,
  },
  durationReliability: {
    minimumReliableMinutes: 12,
    fullReliableMinutes: 20,
    neutralScore: 0.7,
  },
  artifactSoftCap: 4.5,
  artifactOverflow: {
    combat_impact: 0.25,
    risk_discipline: 0.25,
    resource_tempo: 0.25,
    map_objective_control: 0.35,
    team_enablement: 0.2,
  },
  roleExpectations: {
    TOP: {
      assistWeight: 0.7,
      killParticipation: 0.42,
      soloKills: 1.2,
      pickKills: 7,
      damagePerMinute: 650,
      damageShare: 0.22,
      deathRate: 0.16,
      deadTimeShare: 0.105,
      livingRatio: 0.32,
      clutchSurvival: 2,
      goldPerMinute: 400,
      csPerMinute: 7,
      laneCs10: 65,
      visionPerMinute: 0.65,
      wardActivityPerMinute: 0.35,
      objectiveDamagePerMinute: 260,
      epicParticipation: 0.7,
      structureConversion: 1.3,
      ccPerMinute: 1.1,
      ccConversion: 3,
      protectionPerMinute: 45,
      saves: 0.2,
    },
    JUNGLE: {
      assistWeight: 0.85,
      killParticipation: 0.55,
      soloKills: 1,
      pickKills: 10,
      damagePerMinute: 550,
      damageShare: 0.18,
      deathRate: 0.15,
      deadTimeShare: 0.095,
      livingRatio: 0.3,
      clutchSurvival: 2,
      goldPerMinute: 380,
      csPerMinute: 5.6,
      jungleCs10: 55,
      initialCrabs: 1,
      initialBuffs: 2,
      visionPerMinute: 0.85,
      wardActivityPerMinute: 0.3,
      objectiveDamagePerMinute: 520,
      epicParticipation: 2.3,
      structureConversion: 0.8,
      ccPerMinute: 1.3,
      ccConversion: 4,
      protectionPerMinute: 30,
      saves: 0.15,
    },
    MIDDLE: {
      assistWeight: 0.75,
      killParticipation: 0.5,
      soloKills: 1.2,
      pickKills: 9,
      damagePerMinute: 700,
      damageShare: 0.23,
      deathRate: 0.14,
      deadTimeShare: 0.09,
      livingRatio: 0.32,
      clutchSurvival: 2,
      goldPerMinute: 420,
      csPerMinute: 7.3,
      laneCs10: 68,
      visionPerMinute: 0.7,
      wardActivityPerMinute: 0.32,
      objectiveDamagePerMinute: 250,
      epicParticipation: 0.9,
      structureConversion: 1,
      ccPerMinute: 1.2,
      ccConversion: 3.5,
      protectionPerMinute: 35,
      saves: 0.15,
    },
    BOTTOM: {
      assistWeight: 0.65,
      killParticipation: 0.55,
      soloKills: 0.6,
      pickKills: 8,
      damagePerMinute: 780,
      damageShare: 0.27,
      deathRate: 0.13,
      deadTimeShare: 0.085,
      livingRatio: 0.34,
      clutchSurvival: 1.6,
      goldPerMinute: 450,
      csPerMinute: 7.8,
      laneCs10: 70,
      visionPerMinute: 0.55,
      wardActivityPerMinute: 0.24,
      objectiveDamagePerMinute: 360,
      epicParticipation: 1.1,
      structureConversion: 1.2,
      ccPerMinute: 0.6,
      ccConversion: 2.2,
      protectionPerMinute: 25,
      saves: 0.1,
    },
    UTILITY: {
      assistWeight: 1,
      killParticipation: 0.58,
      soloKills: 0.15,
      pickKills: 12,
      damagePerMinute: 330,
      damageShare: 0.1,
      deathRate: 0.16,
      deadTimeShare: 0.1,
      livingRatio: 0.3,
      clutchSurvival: 1.5,
      goldPerMinute: 280,
      csPerMinute: 0.8,
      laneCs10: 5,
      visionPerMinute: 1.8,
      wardActivityPerMinute: 0.75,
      objectiveDamagePerMinute: 90,
      epicParticipation: 1.1,
      structureConversion: 0.4,
      ccPerMinute: 2,
      ccConversion: 5,
      protectionPerMinute: 160,
      saves: 0.7,
    },
    UNKNOWN: {
      assistWeight: 0.75,
      killParticipation: 0.5,
      soloKills: 1,
      pickKills: 8,
      damagePerMinute: 600,
      damageShare: 0.2,
      deathRate: 0.15,
      deadTimeShare: 0.095,
      livingRatio: 0.31,
      clutchSurvival: 1.8,
      goldPerMinute: 380,
      csPerMinute: 6,
      laneCs10: 55,
      jungleCs10: 45,
      initialCrabs: 1,
      initialBuffs: 2,
      visionPerMinute: 0.8,
      wardActivityPerMinute: 0.35,
      objectiveDamagePerMinute: 250,
      epicParticipation: 1,
      structureConversion: 1,
      ccPerMinute: 1.1,
      ccConversion: 3,
      protectionPerMinute: 45,
      saves: 0.2,
    },
  },
  artifactWeights: {
    TOP: {
      combat_impact: [0.55, 0.45],
      risk_discipline: [0.65, 0.35],
      resource_tempo: [0.55, 0.45],
      map_objective_control: [0.35, 0.65],
      team_enablement: [0.9, 0.1],
    },
    JUNGLE: {
      combat_impact: [0.55, 0.45],
      risk_discipline: [0.65, 0.35],
      resource_tempo: [0.45, 0.55],
      map_objective_control: [0.3, 0.7],
      team_enablement: [0.9, 0.1],
    },
    MIDDLE: {
      combat_impact: [0.55, 0.45],
      risk_discipline: [0.65, 0.35],
      resource_tempo: [0.6, 0.4],
      map_objective_control: [0.45, 0.55],
      team_enablement: [0.85, 0.15],
    },
    BOTTOM: {
      combat_impact: [0.45, 0.55],
      risk_discipline: [0.75, 0.25],
      resource_tempo: [0.7, 0.3],
      map_objective_control: [0.35, 0.65],
      team_enablement: [0.8, 0.2],
    },
    UTILITY: {
      combat_impact: [0.7, 0.3],
      risk_discipline: [0.65, 0.35],
      resource_tempo: [0.35, 0.65],
      map_objective_control: [0.7, 0.3],
      team_enablement: [0.55, 0.45],
    },
    UNKNOWN: {
      combat_impact: [0.5, 0.5],
      risk_discipline: [0.65, 0.35],
      resource_tempo: [0.5, 0.5],
      map_objective_control: [0.5, 0.5],
      team_enablement: [0.75, 0.25],
    },
  },
};

const SCORING_CONFIG = {
  minMatchesForMeaningfulScore: 1,
  roleMultipliers: ROLE_MULTIPLIERS,
  deathTolerance: DEATH_TOLERANCE,
  opscoreV2: OPSCORE_V2,
  normalization: {
    floorPercentile: 0.05,
    centerPercentile: 0.5,
    ceilingPercentile: 0.95,
    centerScore: 6.6,
  },
};

module.exports = {
  ...SCORING_CONFIG,
  ROLE_MULTIPLIERS,
  DEATH_TOLERANCE,
  OPSCORE_V2,
};
